name: flutter_food_ordering
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_rating_bar: ^2.0.0+2
  provider: ^4.3.3
  intl: ^0.15.8
  dio: ^3.0.4
  toast: ^0.1.5
  device_info: ^2.0.2
  flutter_secure_storage: ^4.1.0
  flutter_signin_button: ^2.0.0
  lottie: ^1.0.1
  google_sign_in: ^5.0.1
  skeleton_text: ^3.0.0
  flutter_svg: ^0.21.0+1
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  smooth_star_rating: ^1.0.4
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/start.json
    - assets/
    - assets/images/
    - assets/images/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true